---
title: '복구 가능성'
author: 'bayernmuller'
---

### 4.1.1 복구 가능한 오류

* 많은 소프트웨어 오류는 치명적이지 않은 경우가 있음
    * 전화 프로그램에서 유저가 잘못된 번호를 입력 했을 때, 재입력을 요구하면 해야한다.
    * 전체 시스템을 종료할 필요는 없다.

* 그래서 복구가 가능한 오류에 대해서는 표나지 않고 적절하게 처리해야한다.

### 4.1.2 복구할 수 없는 오류

* 오류가 발생했을 때 이를 복구할 수 없을 때도 있다.
    1. 코드와 함께 추가되어야 하는 리소스가 없다.
    2. 잘못된 스펙으로 함수를 호출한다.
    3. 선행되어야 하는 부분을 실행하지 않고 진행한다.

* 위처럼 오류를 복구할 수 있는 방법이 없다면 개발자가 문제를 발견하고 해결할 가능성을 최대화 하는 것이다.
    * 이를 위해 4.2절에서 **신속한 실패 (Fail Fast)**, **요란한 실패 (Failing Loudly)** 를 설명한다.

### 4.1.3 호출하는 쪽에서만 오류 복구 가능 여부를 알 떄가 많다

* 대부분의 오류는 다른 코드를 호출 할 때 발생한다.
* 따라서 아래 사항을 생각해야 한다.
    * 오류로부터 복구하기를 호출하는 쪽에서 원하는가?
    * 만약 그렇다면 오류를 처리할 필요가 있다는 것을 호출 하는 쪽에서 어떻게 알 수 있나?

```python
class PhoneNumber:
    @staticmethod
    def parse(number: str) -> PhoneNumber:
        if not PhoneNumber.isValid(number):
            # 에러 처리 코드

def get_head_office_phone_number() -> PhoneNumber:
    # 하드코딩된 값이기 때문에 오류를 복구할 수 없다.
    return PhoneNumber.parse("1234typo5678")

def get_user_phone_number(user: User) -> PhoneNumber:
    # 유저가 제공한 값이기 때문에 오류를 복구할 수 있다.
    # 오류를 복구할 수 있는지 여부는 호출하는 쪽에 달려있다.
    return PhoneNumber.parse(user.phone_number)
```

* 위 경우에서 `PhoneNumber.parse` 함수는 유효성 검사만 수행하기 때문에 오류를 복구할 수 있는지 정하는 것은 호출하는 쪽에 달려있다.
* 일반적으로 아래 경우 함수에 제공된 값으로 인해 발생하는 오류는 호출하는 쪽에서 복구하고자 하는 것으로 간주된다.
    1. 함수가 어디서 호출될지 그리고 호출 시 제공되는 값이 어디서 올지 완전한 지식이 없을 때
    2. 코드가 미래에 재사용될 가능성이 아주 희박할 때
        * 재사용이 된다는 것은 어디에서 호출되고 값이 어디에서 오는지에 대한 가정이 의미가 없어지기 떄문.

### 4.1.4 호출하는 쪽에서 복구하고자 하는 오류에 대해 인지하도록 하라

* `PhoneNumber.parse` 함수를 호출 하는 입장에서는 어떤 포맷이 valid 한 번호인지 알 필요는 없다.
* 단 이 함수를 호출하는 쪽에서는 전화 번호 형식에 대한 전문 지식이 없어 잘못된 형식의 전화번호가 있다는 생각조차 하지 못할 수 있다.
* 따라서 `PhoneNumber.parse` 함수 작성자는 이 함수에서 오류가 발생할 수 있다는 가능성을 호출하는 쪽이 인지하도록 해야한다.